sudo: false
language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
cache:
  directories:
  - $HOME/.cache/pip
install: pip install tox travis-tox coveralls wheel
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: jazzband
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: jazzband/django-queued-storage
    condition: "$TOXENV = py27-django-110"
  password:
    secure: scGiNi9NXOdVaWzly7Tc65SBbC7iUVkcaO9ibBFfJq2QB0QM7es9QeXhpBz/biHbgCh40zuP8o2XmmsENxyaebb712k657YFS6fAcNmau7txCMOxDceQNoN/2OhSmGpYsegl8EdwBd4HsoB0fpLuq4bUg6OUkVkqR4pe4afq4O0=
